### ISSUE TITLE
License, question.

### ISSUE THREAD

**Issue by mrpsiho** [TryAventum/hooks#1]
Hi!

What you did is very helpful. I would like to use it. Also the fact it is under MIT license, this is what I need. However, I have doubts if you really can license it this way. In the description it is being said that your lib is created on top of @wordpress/hooks, the lib that is licensed under GPL.

So, are you really allowed to set MIT license? Maybe you have to license it under GPL as well?

**Comment by MohammedAl-Mahdawi** [comment]
Hi @mrpsiho 

Thank you for your questing and the nice words, this is a really important topic, unfortunately, I'm not an expert in licensing and I didn't know about this! in the past few days I made some research and found as you described it is better to change it to GPL, I just updated the license and released a new version.
